language: python
python:
  - "3.6"
  - "3.7-dev"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - latexmk

install:
  - pip install -r requirements.txt

script:
  - SPHINXOPTS="-t instructors -nWT" make html latexpdf